# Generated by Django 4.1.2 on 2023-01-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area_info',
            fields=[
                ('city_id', models.IntegerField(max_length=2)),
                ('area_name', models.CharField(max_length=50)),
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='branches',
            fields=[
                ('course_id', models.IntegerField(max_length=2)),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='city_info',
            fields=[
                ('state_id', models.IntegerField(max_length=2)),
                ('city_name', models.CharField(max_length=50)),
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('coursetype_id', models.IntegerField(max_length=2)),
                ('course_name', models.CharField(max_length=100)),
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='coursetypes',
            fields=[
                ('coursetype_name', models.CharField(max_length=100)),
                ('coursetype_id', models.AutoField(primary_key=True, serialize=False)),
                ('coursetype_duration', models.SmallIntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='qualif_info',
            fields=[
                ('user_id', models.IntegerField(max_length=100)),
                ('qualif_id', models.AutoField(primary_key=True, serialize=False)),
                ('coursetype_id', models.IntegerField(max_length=2)),
                ('course_id', models.IntegerField(max_length=2)),
                ('branch_id', models.IntegerField(max_length=2)),
                ('passout_year', models.IntegerField(max_length=4)),
                ('highest_qualif', models.BooleanField()),
                ('aggregate', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('skill_name', models.CharField(max_length=100)),
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='state_info',
            fields=[
                ('state_name', models.CharField(max_length=50)),
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_personal_info',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('mobile_num', models.CharField(db_index=True, max_length=10, unique=True)),
                ('email_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('state_id', models.IntegerField(max_length=2)),
                ('city_id', models.IntegerField(max_length=2)),
                ('area_id', models.IntegerField(max_length=2)),
                ('user_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=10)),
                ('skill_id', models.IntegerField(max_length=10)),
                ('experience', models.SmallIntegerField(max_length=2)),
            ],
        ),
    ]
